version: "3.8"

services:
  vote:    
    image: dle/vote:latest
    build: 
      context: ./vote
      dockerfile: Dockerfile.watch
    volumes: 
      - ./vote/src:/app/src
      - ./vote/public:/app/public
    ports:
      - "3000:3000"
    environment: 
      - CI=true
  result:
    image: dle/result:latest
    build:
      context: ./result
      dockerfile: Dockerfile.watch
    volumes: 
      - ./result/src:/app/src
      - ./result/public:/app/public
    ports:
      - "5000:5000"
      - "3572:3572"
      - "35729:35729"
    environment: 
      - CI=true
      - HOST=0.0.0.0
  worker:
    image: dle/worker:latest
    build:
      context: ./worker
      dockerfile: Dockerfile.watch
    volumes:
      - ./worker/src:/app/src
    ports:
      - "4000:5000"

