version: "3.8"

services:
  vote:    
    image: dle/vote:latest
    build: 
      context: ./vote
      dockerfile: Dockerfile
    ports:
      - "3000:5000"
    networks: 
      - frontend
      - backend
    environment: 
      - CI=true
  result:
    image: dle/result:latest
    build:
      context: ./result
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
      - "3572:3572"
      - "35729:35729"
    networks: 
      - frontend
      - backend
    environment: 
      - CI=true
      - HOST=0.0.0.0
  worker:
    image: dle/worker:latest
    build:
      context: ./worker
      dockerfile: Dockerfile
    ports:
      - "4000:80"
    networks: 
      - backend

networks: 
  frontend:
  backend: