version: "3.8"

services:
  vote:    
    container_name: vote
    build: 
      context: ./vote
      dockerfile: Dockerfile.watch
    volumes: 
      - ./vote/src:/app/src
      - ./vote/public:/app/public
    ports:
      - "3000:3000"
    networks: 
      - frontend
      - backend
    environment: 
      - CI=true
  result:
    container_name: result
    build:
      context: ./result
      dockerfile: Dockerfile.watch
    volumes: 
      - ./result/src:/app/src
      - ./result/public:/app/public
    ports:
      - "5000:5000"
      - "3572:3572"
      - "35729:35729"
    networks: 
      - frontend
      - backend
    environment: 
      - CI=true
      - HOST=0.0.0.0
  worker:
    container_name: worker
    build:
      context: ./worker
      dockerfile: Dockerfile.watch
    volumes:
      - ./worker/src:/app/src
    ports:
      - "4000:4000"
    networks: 
      - backend
  api:
    container_name: api
    build:
      context: ./api
      dockerfile: Dockerfile.watch
    ports:
      - "8080:8080"
    volumes:
      - ./api/src:/app/src
    networks: 
      - backend

networks: 
  frontend:
  backend: