apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.21.0 (992df58d8)
  labels:
    io.kompose.service: worker
  name: worker-service
  namespace: my-vote
spec:
  ports:
  - name: "4000"
    port: 4000
    targetPort: 80
  selector:
    io.kompose.service: worker
  type: LoadBalancer
status:
  loadBalancer: {}
